
name: build

permissions:
  contents: write

# Controls when the action will run.
on:
  schedule:
    - cron: "0 0 * * 1" # weekly
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Matrix strategy from
    # https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            shell: powershell
            arch: x86_64
          - os: ubuntu-22.04
            shell: bash

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      MSYS2_DIR: C:\msys64
      WINLIBS_FILE_NAME_STEM: "winlibs-x86_64-posix-seh-gcc-13.0.1-snapshot20230305-mingw-w64ucrt-10.0.0"
      WINLIBS_DOWNLOAD_PATH: "https://github.com/brechtsanders/winlibs_mingw/releases/download/13.0.1-snapshot20230305-10.0.0-ucrt-r1/winlibs-x86_64-posix-seh-gcc-13.0.1-snapshot20230305-mingw-w64ucrt-10.0.0-r1.zip"
      EMACS_REPO: https://github.com/kiennq/emacs.git
      

    defaults:
      run:
        shell: ${{ matrix.shell }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup msys2
      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          release: false
      # This is the shortest job, but in this case it pulls all MSYS/MINGW64
      - name: Download WinLibs MinGW
        uses: carlosperate/download-file-action@v1.0.3
        with:
            file-url: 'https://github.com/brechtsanders/winlibs_mingw/releases/download/13.0.1-snapshot20230305-10.0.0-ucrt-r1/winlibs-x86_64-posix-seh-gcc-13.0.1-snapshot20230305-mingw-w64ucrt-10.0.0-r1.zip'
            file-name: 'mingw.zip'
            location: './'
      - name: Extract MinGW
        run: Expand-Archive ./mingw.zip -DestinationPath ~/$env:WINLIBS_FILE_NAME_STEM
        #mingw64
      - name: Remove OldMinGW
        run: remove-item -recurse -force  C:\msys64\mingw64
        #mingw64
      - name: Copy NewMinGW
        run: Move-Item -Path $env:WINLIBS_FILE_NAME_STEM\mingw64 -Destination $env:MSYS2_DIR
        #mingw64
